// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvwCzNFXBfBNR9Ewm4yjtC3VR8R5yVOVA',
    appId: '1:790519685617:web:01ab213791c417fe4e2450',
    messagingSenderId: '790519685617',
    projectId: 'travelapp-9a19a',
    authDomain: 'travelapp-9a19a.firebaseapp.com',
    storageBucket: 'travelapp-9a19a.firebasestorage.app',
    measurementId: 'G-N1PZESW8DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQWYaA9rZwCYKSNkybmhhwbRdmQd60Lg',
    appId: '1:790519685617:android:7e9839b071dfb10f4e2450',
    messagingSenderId: '790519685617',
    projectId: 'travelapp-9a19a',
    storageBucket: 'travelapp-9a19a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqZwBq2hWKgmDGJ590ZegvCtbe4hw44k',
    appId: '1:790519685617:ios:dcc93b5fe138ad1f4e2450',
    messagingSenderId: '790519685617',
    projectId: 'travelapp-9a19a',
    storageBucket: 'travelapp-9a19a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMqZwBq2hWKgmDGJ590ZegvCtbe4hw44k',
    appId: '1:790519685617:ios:dcc93b5fe138ad1f4e2450',
    messagingSenderId: '790519685617',
    projectId: 'travelapp-9a19a',
    storageBucket: 'travelapp-9a19a.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvwCzNFXBfBNR9Ewm4yjtC3VR8R5yVOVA',
    appId: '1:790519685617:web:7363fb10913588014e2450',
    messagingSenderId: '790519685617',
    projectId: 'travelapp-9a19a',
    authDomain: 'travelapp-9a19a.firebaseapp.com',
    storageBucket: 'travelapp-9a19a.firebasestorage.app',
    measurementId: 'G-JXG3VFTHJ9',
  );

}